### ISSUE TITLE
Missing "nop" instruction on Legacy of Kain: Soul Reaver function

### ISSUE THREAD

**Issue by FedericoMilesi** [mkst/maspsx#101]
Hi,

I noticed this function matches 100% with the regular PsyQ configuration, but it is missing a "nop" when using the current preset for the game:

https://decomp.me/scratch/tfImt

Kind regards, 
Federico.

**Comment by mkst** [comment]
Nice bug. Should be easy to fix. maspsx doesnt currently worry about whether to place a nop if a %lo() macro is used.

```as
	lw	$5,%lo(objectAccess+204)($2)
$L3:
	beq	$5,$0,$L4
```

**Comment by mkst** [comment]
The change has been deployed to decomp.me :+1:
