### ISSUE TITLE
Possible maspsx bug in Legacy of Kain: Soul Reaver function?

### ISSUE THREAD

**Issue by FedericoMilesi** [mkst/maspsx#105]
Hi,

I have been decompiling this function for a while, it's the third largest one from the game, so there's a lot going on in here but it's currently 99.95% matched: https://decomp.me/scratch/853nW

Only thing that is preventing from getting a 100% match is a misplaced instruction, but, I wonder if it isn't a maspsx bug because using the PsyQ 4.3 config even though the matching percent gets bogged down to 92.60% due to extra division code and such, the relevant subu instruction is correctly placed then. 

Kind regards, 
Federico.

**Comment by mkst** [comment]
Let me investigate, does look like a maspsx issue, but not sure why the subu/nop is ordered that way.

This is using psyq (only $gp differences?) on mobile: https://decomp.me/scratch/vV9eT

**Comment by mkst** [comment]
Interestingly, the diff when using PSYQ suggests Legacy of Kain uses ASPSX 2.81

**Comment by mkst** [comment]
Latest maspsx deployed to decomp.me (your scratch is now :ok:)

![image](https://github.com/user-attachments/assets/363d89e0-68cf-40ca-bdb6-559077b8486b)

**Comment by FedericoMilesi** [comment]
Thanks for the attention, I am glad to finally be able to get this function into the project since it's the second largest function written in C and nets quite a nice amount of matching bytes.
