### ISSUE TITLE
Another mismatching NOP

### ISSUE THREAD

**Issue by bismurphy** [mkst/maspsx#22]
Hi!

As part of the SOTN decomp, I've been working on a large function, and I've found a divergence in maspsx's output.

Here is a decomp.me scratch: https://decomp.me/scratch/gAkz5

If you scroll to assembly line 434, there is an extra NOP inserted, likely as a result of having a `lw` instruction immediately followed by another instruction which uses that same register. With the settings as-is, this NOP is missing from the compiled code. Changing the Options to use the SOTN preset on decomp.me restores the NOP, which I believe indicates that this is a maspsx issue.

**Comment by mkst** [comment]
On master I see (at least) two issues:
Extra `nop` here on the branch:
![image](https://github.com/mkst/maspsx/assets/22226349/de9b7ea4-62d4-41cd-aade-4e1bfcdbf6ac)
Missing `nop` here:
![image](https://github.com/mkst/maspsx/assets/22226349/f19d44fc-fe63-433e-96b0-b89bf1fd6e1a)
