### ISSUE TITLE
Non-matching scratch.

### ISSUE THREAD

**Issue by Kneesnap** [mkst/maspsx#26]
The following scratch does not assemble with masmpsx, because it is missing the nop at 0xB4 (gte_SetRotMatrix on line 41): https://decomp.me/scratch/ycPYA

Compilers Tested:
 - PsyQ 3.5 (GCC 2.6.0 without maspsx) -> Matches
 - GCC 2.6.0 (with maspsx) ->Does not Match
 - GCC 2.6.3 (with maspsx) ->Does not Match

**Comment by mkst** [comment]
The issue is that the macro is injected and maspsx doesn't handle the fact there are multiple commands on a single line:

```as
	lw	$18,4($2)
	lw	$20,40($2)
	lw	$19,44($2)
	lw	$2,20($2)
  
 #APP
	lw	$12, 0( $2 );lw	$13, 4( $2 );ctc2	$12, $0;ctc2	$13, $1;lw	$12, 8( $2 );lw	$13, 12( $2 );lw	$14, 16( $2 );ctc2	$12, $2;ctc2	$13, $3;ctc2	$14, $4
 #NO_APP

  #nop
	move	$2,$18
```

A fix would be to properly parse multiple statements on a single line, as maspsx should know to insert a `nop` here:

```as
	lw	$2,20($2)
	nop; we need this because the next instruction reads from $2 (aka $v0)
	lw	$12, 0( $2 )
```
