### ISSUE TITLE
Operand 2 must be constant `addu $at,None,$at'

### ISSUE THREAD

**Issue by Xeeynamo** [mkst/maspsx#29]
I noticed MASPSX produces malformed assembly. I trimmed down to the bare minimum the function I am working on to reproduce the issue: https://decomp.me/scratch/urXVb

**Comment by mkst** [comment]
Closed via https://github.com/mkst/maspsx/commit/ae43f009e319d55362423e2bc1fb96bc7d55aa47 :)
