### ISSUE TITLE
Undefined reference to `$L31'

### ISSUE THREAD

**Issue by Xeeynamo** [mkst/maspsx#8]
This is a use scenario I missed in my previous PRs. I looked into it but I have no clue how to fix it.

On https://github.com/Xeeynamo/sotn-decomp/pull/330 the function `DebugCaptureScreen` has the line `u16 pixelColor = src[j + i * width];`. That multiplication generates the assembly that would be patched as faulty.

If you need any additional info or any help on how to reproduce this, please ping me on Discord!

### Unpatched assembly

```
	mult	$17,$19
	move	$21,$5
	mflo	$18
$L31:

	.loc	1 140
LM82:
```

```
	.loc	1 155
LM94:
$Le4:
	.bend	$Le4	87

	.loc	1 139
LM95:
$L30:
	addu	$17,$17,-1
	.set	noreorder
	.set	nomacro
	bgez	$17,$L31
	subu	$18,$18,$19
	.set	macro
	.set	reorder
```

### Patched assembly

```
mult	$17,$19
move	$21,$5
mflo	$18
# $L31:  # DEBUG: skipped

	.loc	1 140
LM82:
```

```
.loc	1 155
LM94:
$Le4:

.loc	1 139
LM95:
$L30:
addu	$17,$17,-1
bgez	$17,$L31
subu	$18,$18,$19
```

**Comment by mkst** [comment]
Yeh, I had a feeling that the logic would be insufficient if the next instruction *wasn't* a nop, so just need to add some logic to handle labels. I'll look into this as soon as I get a chance :)
