### ISSUE TITLE
Legacy of Kain: Soul Reaver function won't compile on MASPSX 

### ISSUE THREAD

**Issue by FedericoMilesi** [mkst/maspsx#84]
mcassert is a function that is currently 100% matched using inlined asm, however the solution while compiling with PSYQ 4.4 won't work with the current maspsx preset for Legacy of Kain: Soul Reaver on decomp.me as can be seen in the following scratch:

https://decomp.me/scratch/WumtK

**Comment by mkst** [comment]
Closed via https://github.com/mkst/maspsx/commit/ef30355e943f7b66ada13b3422500880100d5f38
