### ISSUE TITLE
Mismatching scratch (ASPSX v2.21)

### ISSUE THREAD

**Issue by shao113** [mkst/maspsx#85]
https://decomp.me/scratch/dVIjN

When switching to maspsx with --aspsx-version=2.21, there are some differences starting at 4e0 and 520.

**Comment by mkst** [comment]
Thanks for the bug report, I'm looking into it :+1:

Scratch: https://decomp.me/scratch/Lgryk

Two issues:
- `lui a2,0xff` vs `lui a2,0x100`
- `addu at,a0,at` vs  `addu at,a0,at`

![image](https://github.com/user-attachments/assets/106efe44-36e9-4f8d-947a-6d5ec6ff0159)
