### ISSUE TITLE
Extra nops after mflo (ASPSX v2.21)

### ISSUE THREAD

**Issue by shao113** [mkst/maspsx#90]
https://decomp.me/scratch/8ilKx (Starting at 328)

![maspsx-extra-nops](https://github.com/user-attachments/assets/f73083d1-ea5c-488f-a27c-bbe1e6e2eca3)

**Comment by mkst** [comment]
Wow! This looks like this is buggy behaviour in ASPSX 2.21 not ensuring there are 2 instructions between mult/mflo instructions (ASPSX 2.34 puts the nops in)

**Comment by mkst** [comment]
Latest version deployed to decomp.me - that scratch is now :ok:
