### ISSUE TITLE
Potential `nop` generating bug

### ISSUE THREAD

**Issue by bismurphy** [mkst/maspsx#97]
I was working on a function for Castlevania:SOTN and I seem to have a `nop` in the Target that won't generate with maspsx, but does generate with aspsx.

Decomp.me scratch is here: https://decomp.me/scratch/RVSDy

The missing `nop` is at ASM line 458. 

If I change the compiler to PSYQ3.5, then the `nop` instruction is emitted, but the default SOTN preset (gcc 2.6.3 + maspsx) does not generate that NOP.

Maybe this isn't a maspsx issue, but it feels like one, since the single instruction differs here. My function mismatches in other ways, but this `nop` jumped out at me as something you may want to look into. Presumably this is related to the fact that instruction 454 is a `lw` targeting the `s1` register, and then 45c is a `lh` loading from an offset of that `s1` pointer.

**Comment by mkst** [comment]
Interestingly enough, the `nop` is present without the `-gcoff` flag, so maspsx isnt handling all the extra noise that `-gcoff` adds. Hopefully easy to fix.

**Comment by bismurphy** [comment]
> Will test in a couple of hours and release if it solves it - thanks for raising the issue!

Awesome, thanks as always! Really appreciate how much you help with everything.
